version: '3.1'

services:
  easecart-mysql:
    image: mysql
    restart: always
    container_name: "ease-cart-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3307:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - ease-cart-mysql-data:/var/lib/mysql

  easecart-redis:
    image: "redis:latest"
    container_name: "ease-cart-redis-container"
    ports:
      - "6379:6379"
    volumes:
      - ease-cart-redis-data:/data

volumes:
  ease-cart-redis-data:
  ease-cart-mysql-data: