
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ease-cart
    username: root
    password: password
  application:
    name: EaseCart
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true