
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easecart
    username: root
    password: password
  application:
    name: easecart
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  mail:
        host: smtp.gmail.com
        port: 587
        username: miha.caks1@student.um.si
        password: vugbum!-pijsY7!-qybzeh!
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true